# Generated by Django 4.1.6 on 2023-05-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('subtitle', models.CharField(default=' ', max_length=100)),
                ('text', models.CharField(max_length=5000)),
                ('thumb', models.CharField(max_length=200)),
                ('date', models.CharField(default=' ', max_length=100)),
                ('category', models.CharField(default=' ', max_length=20)),
            ],
        ),
    ]
