# Generated by Django 3.2.19 on 2023-07-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_new_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='company',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='new',
            name='logo',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
