# Generated by Django 3.2.19 on 2023-07-11 20:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20230711_1558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='date',
        ),
        migrations.RemoveField(
            model_name='new',
            name='logo',
        ),
        migrations.AddField(
            model_name='new',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
